version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - run: npm install
      - run: npm rebuild node-sass # Bug fix
      - run: npm run build:prod
  deploy:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - run: node .circleci/deploy.js
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master