version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/tmp
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - run: npm install
      - run: npm rebuild node-sass # Bug fix
      - run: npm run build:prod
      - persist_to_workspace:
          root: .
          paths:
            - .circleci # Deploy script
            - dist # statics to deploy
  deploy:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/tmp
    steps:
      - attach_workspace:
          at: /tmp
      - run: ls
      - run: node .circleci/deploy.js
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop