version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.5.0
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          key: node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install build environment
          command: sudo npm install -g npm@latest && npm install && npm rebuild node-sass # npm rebuild node-sass is a bug fix
      - save_cache:
          name: Save node modules cache
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build project
          command: npm run build:package
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - dist
            - .circleci
  deploy:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/workspace
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: npm install sftp-sync-deploy
      - run: node .circleci/deploy.js
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
